modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/cassiancc/Raspberry-Core/issues"
license = "MIT"

[[mods]]
modId = "raspberry"
version = "${version}"
displayName = "Raspberry Core"
authors = "cassiancc, DavigJ"
description = '''
Various compatibility blocks and fixes for the Raspberry Flavoured modpack.
'''
#logoFile = ""

[[dependencies.raspberry]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.19.2-1.2.4,)"
ordering = "AFTER"
side = "BOTH"
